name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Thay 'main' bằng tên nhánh bạn muốn triển khai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cPanel CLI
        run: npm install -g cpanel-cli  # Đảm bảo cPanel CLI đã được cài đặt trước

      - name: Deploy to cPanel
        env:
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
        run: |
          echo "Committing changes to cPanel git version control..."
          cpanel-git push --all
